# config/pipeline.yml

# Building blocks for ETL Classes
extractors:
  NYC_Open:
    class: ETL.extractors.nyc_open.Raw_NYC_Open
    params:
      domain: 'data.cityofnewyork.us'
      uri_id: '43nn-pn8j'
      nyc_open_key: ${env:nyc_open_key}
      years_cutoff: 7
      row_limit: 1000000
  from_postgres:
    class: ETL.extractors.sql_db.Postgres_Features
    params: {}

transformers:
  main_cleaner:
    class: ETL.transformers.nyc_open.NYC_Open_Cleaner
    params: {}
  ml_preprocess:
    class: ETL.transformers.sql_db.Preprocess_ML_Data
    params: {}

loaders:
  to_postgres:
    class: ETL.loaders.nyc_open.Load_Inspections
    params:
      constraint_name: 'uq_inspection_natural'

# Putting pipelines together
pipelines:
  get_data:
    extractors: [ NYC_Open ]
    transformers: [ main_cleaner ]
    loaders: [ to_postgres ]

  train_model:
    extractors: [ from_postgres ]
    transformers: [ ml_preprocess ]
    loaders: [  ]

# Grouping pipelines together
tasks:
  all:
    pipelines: [ get_data, train_model ]