# config/pipeline.yml

# Building blocks for ETL Classes
extractors:
  NYC_Open:
    class: ETL.extractors.nyc_open.NYC_Restaurants
    params:
      url:
      api_key: ${env:nyc_open_key}
      sleep: 10
      timeout: 15
      delay: 10
      retry: 2
      years_cutoff: 2
      row_limit: 200000
  Census:
    class:
    params:
      url:
      api_key: ${env:census_key}
      sleep:
      timeout:

transformers:
  transformerName:
    class:
    params: {}
  nextTransformer:
    class:
    params: {}

loaders:
  postgres:
    class:
    params:
      dataset:
      table:

# Putting pipelines together
pipelines:
  startup:
    extractors: [ NYC_Open, Census ]
    concat: true
    transformers: [ transformerName, nextTransformer ]
    loaders: [ postgres ]

  biweekly_update:
    extractors: [ NYC_Open]
    concat: false
    transformers: [ transformerName, nextTransformer ]
    loaders: [ postgres ]

# Grouping pipelines together
tasks:
  name1:
    pipelines: [ startup, biweekly_update ]
  name2:
    pipelines: [ startup ]