# config/pipeline.yml

# Building blocks for ETL Classes
extractors:
  nyc_open:
    class: ETL.extractors.nyc_open.RawInspectionData
    params:
      domain: 'data.cityofnewyork.us'
      uri_id: '43nn-pn8j'
      nyc_open_key: ${env:nyc_open_key}
      years_cutoff: 7
      row_limit: 1000000
  from_postgres:
    class: ETL.extractors.sql_db.FromInspectionDB
    params: {}

transformers:
  df_cleaner:
    class: ETL.transformers.nyc_open.InspectionCleaner
    params: {}
  ml_preprocess:
    class: ETL.transformers.sql_to_ml.MLPreprocess
    params: {}

loaders:
  to_postgres:
    class: ETL.loaders.nyc_open.InspectionsLoader
    params:
      constraint_name: 'uq_inspection_natural'

# Putting pipelines together
pipelines:
  get_data:
    extractors: [ nyc_open ]
    transformers: [ df_cleaner ]
    loaders: [ to_postgres ]

  train_model:
    extractors: [ from_postgres ]
    transformers: [ ml_preprocess ]
    loaders: [  ]

# Grouping pipelines together
tasks:
  all:
    pipelines: [ get_data, train_model ]